version: "3.7"
services:
  web:
    container_name: php7_apache_oci8
    build: .
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html/
      - ./conf/apache:/etc/apache2/sites-enabled/
      # - ./conf/php:/usr/local/etc/php/

